global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m
  receiver: webhook

receivers:
  - name: webhook
    webhook_configs:
      - url: "http://alert_receiver:5001/webhook"
        send_resolved: true
