apiVersion: 1

users:
  - name: Viewer
    email: viewer@monitoring.local
    login: viewer
    password: viewer123
    orgId: 1

orgs:
  - name: Main Org
    id: 1

org_users:
  - orgId: 1
    userId: 2
    role: Viewer
